/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

// Callback function types for C# interop
typedef void (*ProgressCallback)(char* itemID, int progress, long long bytesProcessed, long long totalBytes);
typedef void (*StatusCallback)(char* itemID, char* status, char* errorMsg);
typedef void (*QueueUpdateCallback)(char* statsJson);

// Helper functions to call function pointers
static inline void call_progress_callback(ProgressCallback cb, char* itemID, int progress, long long bytesProcessed, long long totalBytes) {
	if (cb != NULL) {
		cb(itemID, progress, bytesProcessed, totalBytes);
	}
}

static inline void call_status_callback(StatusCallback cb, char* itemID, char* status, char* errorMsg) {
	if (cb != NULL) {
		cb(itemID, status, errorMsg);
	}
}

static inline void call_queue_update_callback(QueueUpdateCallback cb, char* statsJson) {
	if (cb != NULL) {
		cb(statsJson);
	}
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) int InitializeApp(char* configPath);
extern __declspec(dllexport) void ShutdownApp(void);
extern __declspec(dllexport) void SetProgressCallback(ProgressCallback callback);
extern __declspec(dllexport) void SetStatusCallback(StatusCallback callback);
extern __declspec(dllexport) void SetQueueUpdateCallback(QueueUpdateCallback callback);
extern __declspec(dllexport) void FreeString(char* str);
extern __declspec(dllexport) char* Search(char* query, char* searchType, int limit);
extern __declspec(dllexport) char* GetAlbum(char* albumID);
extern __declspec(dllexport) char* GetArtist(char* artistID);
extern __declspec(dllexport) char* GetArtistAlbums(char* artistID, int limit);
extern __declspec(dllexport) char* GetPlaylist(char* playlistID);
extern __declspec(dllexport) char* GetCharts(int limit);
extern __declspec(dllexport) char* GetEditorialReleases(int limit);
extern __declspec(dllexport) int DownloadTrack(char* trackID, char* quality);
extern __declspec(dllexport) int DownloadAlbum(char* albumID, char* quality);
extern __declspec(dllexport) int DownloadPlaylist(char* playlistID, char* quality);
extern __declspec(dllexport) int DownloadCustomPlaylist(char* playlistJSON, char* quality);
extern __declspec(dllexport) char* ConvertSpotifyURL(char* url);
extern __declspec(dllexport) char* GetQueue(int offset, int limit, char* filter);
extern __declspec(dllexport) char* GetQueueStats(void);
extern __declspec(dllexport) int PauseDownload(char* itemID);
extern __declspec(dllexport) int ResumeDownload(char* itemID);
extern __declspec(dllexport) int CancelDownload(char* itemID);
extern __declspec(dllexport) int RetryDownload(char* itemID);
extern __declspec(dllexport) int ClearCompleted(void);
extern __declspec(dllexport) char* GetSettings(void);
extern __declspec(dllexport) int UpdateSettings(char* settingsJSON);
extern __declspec(dllexport) char* GetDownloadPath(void);
extern __declspec(dllexport) int SetDownloadPath(char* path);
extern __declspec(dllexport) char* GetVersion(void);
extern __declspec(dllexport) int CheckMigrationNeeded(void);
extern __declspec(dllexport) char* GetMigrationInfo(void);
extern __declspec(dllexport) char* DetectPythonInstallation(void);
extern __declspec(dllexport) char* PerformMigration(ProgressCallback progressCallback);
extern __declspec(dllexport) char* GetMigrationStats(void);
extern __declspec(dllexport) int StopAllDownloads(void);

#ifdef __cplusplus
}
#endif
